const CATEGORIES={"Verdures i hortalisses":["carbassó","patata","ceba","tomàquet","pastanaga","enciam","cogombre","pebrot","mongeta tendra"],"Fruites":["poma","pera","plàtan","taronja","préssec","maduixes","raïm","meló","síndria","cireres","albercocs","mango"],"Llegums":["llenties","cigrons","mongetes blanques","pèsols"],"Peix":["salmó","daurada"],"Carn":["hamburguesa de pollastre","hamburguesa de vedella","bistec"],"Entrants saludables":["hummus","guacamole","bastonets de pastanaga","bastonets de cogombre","amanida petita de tomàquet","gaspatxo"],"Fruits secs":["pipes","nous","ametlles","avellanes"],"Complements saludables":["oli d’oliva","iogurt natural","formatge fresc","arròs blanc","pasta de colors","ou dur"],"Opcions ocasionals":["croquetes de ceps","croquetes de rostit"]};
const RESTRICCIONS=[["senseFruitsSecs","Sense fruits secs"],["senseLactis","Sense lactis"],["senseOu","Sense ou"],["senseGluten","Sense gluten"],["vegetaria","Vegetarià"],["senseCarn","Sense carn"],["sensePeix","Sense peix"]];
const DIES=["Dilluns","Dimarts","Dimecres","Dijous","Divendres","Dissabte","Diumenge"];
const FRUITES_TEMPORADA={primavera:["poma","pera","taronja","maduixes","cireres","albercocs"],estiu:["poma","pera","préssec","maduixes","meló","síndria","cireres","albercocs","mango"],tardor:["poma","pera","plàtan","raïm","mango"],hivern:["poma","pera","plàtan","taronja","mango"],tot:["poma","pera","plàtan","taronja","préssec","maduixes","raïm","meló","síndria","cireres","albercocs","mango"]};
function rec(o){return o}
const receptesBase=[
rec({nom:"Crema de carbassó, patata i ceba",tipus:"crema",categoria:"vegetal",ingredients:["carbassó","patata","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["crema","calent","suau","vegetarià","sense gluten","sense lactis"],temporada:["tot","hivern","tardor"],preparacio:"Coure el carbassó, la patata i la ceba. Triturar i afegir oli d’oliva.",maxSetmana:2,alergens:[]}),
rec({nom:"Crema de pastanaga i patata",tipus:"crema",categoria:"vegetal",ingredients:["pastanaga","patata","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["crema","calent","suau","vegetarià","sense gluten","sense lactis"],temporada:["tot","hivern","tardor"],preparacio:"Coure la pastanaga, la patata i la ceba. Triturar fins a obtenir una textura suau.",maxSetmana:2,alergens:[]}),
rec({nom:"Crema de mongeta tendra i patata",tipus:"crema",categoria:"vegetal",ingredients:["mongeta tendra","patata","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["crema","calent","suau","vegetarià","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Bullir la mongeta tendra amb patata i ceba. Triturar i afegir oli d’oliva.",maxSetmana:2,alergens:[]}),
rec({nom:"Gaspatxo suau amb tomàquet i cogombre",tipus:"entrant",categoria:"entrant",ingredients:["gaspatxo","tomàquet","cogombre","pebrot","oli d’oliva"],apat:["dinar"],etiquetes:["entrant","fred","vegetarià","sense gluten","sense lactis","estiu"],temporada:["estiu","primavera"],preparacio:"Triturar tomàquet, cogombre i pebrot amb oli d’oliva. Servir fred com a entrant de dinar.",maxSetmana:3,alergens:[]}),
rec({nom:"Amanida petita de tomàquet i cogombre",tipus:"entrant",categoria:"vegetal",ingredients:["tomàquet","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["entrant","amanida","fred","vegetarià","sense gluten","sense lactis"],temporada:["tot","estiu","primavera"],preparacio:"Tallar tomàquet i cogombre. Amanir amb oli d’oliva.",maxSetmana:3,alergens:[]}),
rec({nom:"Hummus amb bastonets de pastanaga i cogombre",tipus:"entrant",categoria:"llegums",ingredients:["hummus","cigrons","pastanaga","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["entrant","llegums","fred","vegetarià","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Preparar hummus i servir-lo amb bastonets de pastanaga i cogombre.",maxSetmana:2,alergens:[]}),
rec({nom:"Guacamole amb bastonets de cogombre",tipus:"entrant",categoria:"entrant",ingredients:["guacamole","tomàquet","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["entrant","fred","vegetarià","sense lactis","sense gluten"],temporada:["tot","estiu"],preparacio:"Aixafar l’alvocat i barrejar-lo amb tomàquet tallat petit. Servir amb cogombre.",maxSetmana:2,alergens:[]}),
rec({nom:"Amanida freda de llenties amb poma i tomàquet",tipus:"amanida",categoria:"llegums",ingredients:["llenties","poma","tomàquet","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["amanida","fred","llegums","fruita","vegetarià","sense gluten","sense lactis"],temporada:["tot","estiu","primavera"],preparacio:"Barrejar llenties amb poma, tomàquet i una mica de ceba suau.",maxSetmana:2,alergens:[]}),
rec({nom:"Amanida de cigrons amb pera, tomàquet i cogombre",tipus:"amanida",categoria:"llegums",ingredients:["cigrons","pera","tomàquet","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["amanida","fred","llegums","fruita","vegetarià","sense gluten","sense lactis"],temporada:["tot","estiu","primavera"],preparacio:"Barrejar cigrons amb pera, tomàquet i cogombre. Servir fred.",maxSetmana:2,alergens:[]}),
rec({nom:"Amanida de mongetes blanques amb tomàquet i poma",tipus:"amanida",categoria:"llegums",ingredients:["mongetes blanques","tomàquet","poma","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["amanida","fred","llegums","fruita","vegetarià","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Barrejar mongetes blanques amb tomàquet, poma i ceba suau.",maxSetmana:2,alergens:[]}),
rec({nom:"Amanida de patata, tomàquet i cigrons",tipus:"amanida",categoria:"llegums",ingredients:["patata","tomàquet","cigrons","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["amanida","fred","llegums","vegetarià","sense gluten","sense lactis"],temporada:["tot","estiu"],preparacio:"Coure patata, refredar-la i barrejar-la amb tomàquet, cigrons i ceba suau.",maxSetmana:2,alergens:[]}),
rec({nom:"Pasta de colors amb tomàquet i cigrons",tipus:"pasta",categoria:"llegums",ingredients:["pasta de colors","tomàquet","cigrons","oli d’oliva"],apat:["dinar"],etiquetes:["pasta","fred","llegums","vegetarià","sense lactis"],temporada:["tot","estiu"],preparacio:"Coure la pasta de colors, refredar-la i barrejar-la amb tomàquet, cigrons i oli d’oliva.",maxSetmana:2,alergens:["gluten"]}),
rec({nom:"Arròs blanc amb llenties i amanida de tomàquet",tipus:"arros",categoria:"llegums",ingredients:["arròs blanc","llenties","tomàquet","enciam","oli d’oliva"],apat:["dinar"],etiquetes:["arròs","llegums","amanida","vegetarià","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Servir arròs blanc amb llenties i una amanida fresca de tomàquet i enciam.",maxSetmana:2,alergens:[]}),
rec({nom:"Arròs blanc amb pollastre i amanida",tipus:"arros",categoria:"carn",ingredients:["arròs blanc","hamburguesa de pollastre","enciam","tomàquet","oli d’oliva"],apat:["dinar"],etiquetes:["arròs","carn","amanida","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Acompanyar arròs blanc amb pollastre a la planxa i amanida de tomàquet.",maxSetmana:1,alergens:[]}),
rec({nom:"Salmó al vapor amb patata i mongeta tendra",tipus:"peix",categoria:"peix",ingredients:["salmó","patata","mongeta tendra","oli d’oliva"],apat:["sopar"],etiquetes:["peix","calent","sense gluten","sense lactis","plat principal","sopar"],temporada:["tot"],preparacio:"Coure el salmó al vapor i acompanyar-lo amb patata i mongeta tendra.",maxSetmana:1,alergens:["peix"]}),
rec({nom:"Daurada al vapor amb amanida de tomàquet",tipus:"peix",categoria:"peix",ingredients:["daurada","tomàquet","enciam","cogombre","oli d’oliva"],apat:["sopar"],etiquetes:["peix","calent","amanida","sense gluten","sense lactis","plat principal","sopar"],temporada:["tot","estiu"],preparacio:"Coure la daurada al vapor i servir-la amb amanida senzilla de tomàquet.",maxSetmana:1,alergens:["peix"]}),
rec({nom:"Hamburguesa de pollastre amb amanida",tipus:"carn",categoria:"carn",ingredients:["hamburguesa de pollastre","enciam","tomàquet","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["carn","pollastre","calent","sense lactis","plat principal"],temporada:["tot"],preparacio:"Cuinar l’hamburguesa de pollastre a la planxa i servir-la amb amanida fresca.",maxSetmana:1,alergens:[]}),
rec({nom:"Hamburguesa de vedella amb crema de carbassó",tipus:"carn",categoria:"carn",ingredients:["hamburguesa de vedella","carbassó","patata","ceba","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["carn","vedella","calent","crema","plat principal"],temporada:["tot"],preparacio:"Preparar una crema suau de carbassó, patata i ceba i servir-la amb l’hamburguesa.",maxSetmana:1,alergens:[]}),
rec({nom:"Bistec amb amanida de tomàquet",tipus:"carn",categoria:"carn",ingredients:["bistec","tomàquet","enciam","cogombre","oli d’oliva"],apat:["dinar","sopar"],etiquetes:["carn","vedella","calent","amanida","sense gluten","sense lactis"],temporada:["tot"],preparacio:"Fer el bistec a la planxa i servir-lo amb amanida de tomàquet, enciam i cogombre.",maxSetmana:1,alergens:[]}),
rec({nom:"Croquetes de ceps amb amanida",tipus:"ocasional",categoria:"ocasional",ingredients:["croquetes de ceps","enciam","tomàquet","cogombre"],apat:["sopar"],etiquetes:["ocasional","croquetes","calent","plat ocasional","sopar"],temporada:["tot"],preparacio:"Servir les croquetes de ceps amb una amanida fresca. Plat ocasional.",ocasional:true,maxSetmana:1,alergens:["gluten","lactis"]}),
rec({nom:"Croquetes de rostit amb crema de carbassó",tipus:"ocasional",categoria:"ocasional",ingredients:["croquetes de rostit","carbassó","patata","ceba"],apat:["sopar"],etiquetes:["ocasional","croquetes","carn","calent","plat ocasional","sopar"],temporada:["tot"],preparacio:"Servir les croquetes de rostit amb una crema suau. Plat ocasional.",ocasional:true,maxSetmana:1,alergens:["gluten","lactis"]})
];